RABSW-709: Update to latest nnf-ec and remove lint warnings.

diff --git a/config/samples/scripts/wfrXfs b/config/samples/scripts/wfrXfs
--- a/config/samples/scripts/wfrXfs
+++ b/config/samples/scripts/wfrXfs
@@ -5,19 +5,19 @@ DWSPORT=${DWSPORT:-8080}
 NAMESPACE=${NAMESPACE:-default}
 
 rname=$1
-[[ -n $rname ]] || rname="dws-workflow-test-$$"
+[[ -n $rname ]] || rname="dws$$"
 
 data='{'
 data+='  "metadata": {'
-data+='    "name": "##RNAME##",'
-data+='    "namespace": "##NAMESPACE##"'
+data+='    "name": "'$rname'",'
+data+='    "namespace": "'$NAMESPACE'"'
 data+='  },'
 data+='  "kind": "Workflow",'
 data+='  "apiVersion": "dws.cray.hpe.com/v1alpha1",'
 data+='  "spec": {'
 data+='    "desiredState": "proposal",'
 data+='    "dwDirectives": ['
-data+='      "#DW jobdw type=xfs capacity=10TB name=ajf"'
+data+='      "#DW jobdw type=xfs capacity=5GB name='$rname'"'
 data+='    ],'
 data+='    "jobID": 9000001,'
 data+='    "userID": 1001,'
@@ -28,7 +28,7 @@ data+='}'
 echo Attempting to create $rname ...
 jsondata=$(echo $data | sed -e s:##RNAME##:$rname:g -e s:##NAMESPACE##:"$NAMESPACE":g)
 
-admitResponse=$(curl -X POST "http://${DWSHOST}:${DWSPORT}/apis/dws.cray.hpe.com/v1alpha1/namespaces/$NAMESPACE/workflows" -H "Content-Type: application/json" -d "$jsondata")
+admitResponse=$(curl -s -X POST "http://${DWSHOST}:${DWSPORT}/apis/dws.cray.hpe.com/v1alpha1/namespaces/$NAMESPACE/workflows" -H "Content-Type: application/json" -d "$jsondata")
 retCode=$?
 
 # If the curl command failed, then we assume we failed to create the WFR...
@@ -37,12 +37,12 @@ if [ $retCode -ne 0 ]; then
     exit $retCode
 fi
 
-# curl command successful, look at the returned JSON to see if we were successful
-echo "$admitResponse" | \
-jq 'if .kind == "Status"
-	then
-		"Failed to create: $admitResponse"
-	else
-		.metadata.name, .
-	end, .'
-exit $retCode
+# # curl command successful, look at the returned JSON to see if we were successful
+# echo "$admitResponse" | \
+# jq 'if .kind == "Status"
+# 	then
+# 		"Failed to create: $admitResponse"
+# 	else
+# 		.metadata.name, .
+# 	end, .'
+# exit $retCode
